import React from "react";
import type { Metadata } from "next";
import { Inter, Lalezar } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

const lalezar = Lalezar({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lalezar",
});

export const metadata: Metadata = {
  title: "SA E-learning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={`${inter.variable} ${lalezar.variable}`}>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
