import React from "react";
import type { Metadata } from "next";
import { Inter, Lalezar } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar/Navbar";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

const lalezar = Lalezar({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lalezar",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div
          className={`${inter.variable} ${lalezar.variable}  bg-[url('/assets/icons/border-effect.svg')] bg-no-repeat `}
        >
          <Navbar />
          <div className="container">{children}</div>
        </div>
      </body>
    </html>
  );
}
